server:
  port: 8081

logging:
  charset:
    console: utf-8
  level:
    root: error
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%5p) [%15.15t] %clr(%-40.40logger{39}){cyan} %clr(%6L){magenta} : %clr([%X{x-trace-id}]){cyan} %m%n'
